# Generated by Django 2.0.9 on 2019-11-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='biology', max_length=200),
            preserve_default=False,
        ),
    ]
