# Generated by Django 2.0.9 on 2019-11-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
